---
- name: Install Concert on a VM
  hosts: concert
  remote_user: root
  gather_facts: true
  tasks:
    - name: Install Concert
      ansible.builtin.import_role:
        name: ../roles/concert_vm
